name: education_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  chewie: ^1.8.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  equatable: ^2.0.5
  file_icon:
    git:
      url: https://github.com/NonymousMorlock/file_icon
  file_picker: ^8.1.4
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  video_thumbnail: ^0.5.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_ui_auth: ^1.16.0
  uuid: ^4.5.1
  badges: ^3.1.2
  audioplayers: ^6.1.0
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  video_player: ^2.9.2
  step_progress_indicator: ^1.0.2
  youtube_explode_dart: ^2.3.6

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  firebase_auth_mocks: ^0.14.1
  google_sign_in_mocks: ^0.3.0
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
